#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
OUT="$ROOT/docs/architecture/runtime-inventory.md"

python3 - "$ROOT" "$OUT" <<'PY'
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

root = Path(sys.argv[1]).resolve()
out = Path(sys.argv[2]).resolve()

extensions_dir = root / "extensions"
slices_dir = root / "slices"


def parse_extension(extension_dir: Path) -> dict:
    index_file = extension_dir / "index.ts"
    text = index_file.read_text(encoding="utf-8") if index_file.exists() else ""

    commands = sorted(set(re.findall(r'registerCommand\(\s*"([^"]+)"', text)))
    tools = sorted(set(re.findall(r'registerTool\(\s*\{[\s\S]*?name:\s*"([^"]+)"', text)))

    tests = sorted((extension_dir / "__tests__").glob("*.test.ts")) if (extension_dir / "__tests__").exists() else []

    return {
        "name": extension_dir.name,
        "commands": commands,
        "tools": tools,
        "test_files": len(tests),
    }


extensions = []
for ext_dir in sorted(p for p in extensions_dir.iterdir() if p.is_dir()):
    if (ext_dir / "index.ts").exists():
        extensions.append(parse_extension(ext_dir))

slices = {}
for slice_file in sorted(slices_dir.glob("*.json")):
    data = json.loads(slice_file.read_text(encoding="utf-8"))
    ext_refs = [Path(item).parts[-2] for item in data.get("extensions", []) if isinstance(item, str) and item.endswith("/index.ts")]
    slices[slice_file.stem] = {
        "description": str(data.get("description", "")).strip(),
        "defaultProfile": str(data.get("defaultProfile", "")).strip() or "(none)",
        "extensions": ext_refs,
    }

pipeline_file = root / "agents" / "pipelines.yaml"
pipeline_names = []
if pipeline_file.exists():
    for line in pipeline_file.read_text(encoding="utf-8").splitlines():
        if re.match(r"^[a-zA-Z0-9_-]+:\s*$", line):
            pipeline_names.append(line.split(":", 1)[0])

team_file = root / "agents" / "teams.yaml"
team_names = []
if team_file.exists():
    for line in team_file.read_text(encoding="utf-8").splitlines():
        if re.match(r"^[a-zA-Z0-9_-]+:\s*$", line):
            team_names.append(line.split(":", 1)[0])

lines: list[str] = []
lines.append("# Runtime Inventory (Generated)")
lines.append("")
lines.append("> Generated by `scripts/gen-runtime-inventory.sh`. Commit this file after runtime composition changes.")
lines.append("")
lines.append("## Extension Inventory")
lines.append("")
lines.append("| Extension | Commands | Tools | Test files |")
lines.append("|---|---:|---:|---:|")
for ext in extensions:
    lines.append(f"| `{ext['name']}` | {len(ext['commands'])} | {len(ext['tools'])} | {ext['test_files']} |")

lines.append("")
lines.append("## Extension Command + Tool Surface")
lines.append("")
for ext in extensions:
    lines.append(f"### {ext['name']}")
    commands = ", ".join(f"`/{item}`" for item in ext["commands"]) or "(none)"
    tools = ", ".join(f"`{item}`" for item in ext["tools"]) or "(none)"
    lines.append(f"- commands: {commands}")
    lines.append(f"- tools: {tools}")
    lines.append("")

lines.append("## Slice Composition")
lines.append("")
for name, spec in slices.items():
    lines.append(f"### {name}")
    lines.append(f"- default profile: `{spec['defaultProfile']}`")
    if spec["description"]:
        lines.append(f"- description: {spec['description']}")
    ext_list = ", ".join(f"`{item}`" for item in spec["extensions"]) or "(none)"
    lines.append(f"- extensions: {ext_list}")
    lines.append("")

lines.append("## Orchestration Catalog")
lines.append("")
lines.append(f"- teams ({len(team_names)}): {', '.join(f'`{name}`' for name in team_names)}")
lines.append(f"- pipelines ({len(pipeline_names)}): {', '.join(f'`{name}`' for name in pipeline_names)}")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
print(f"wrote {out}")
PY
